import { motion } from "motion/react";
import { useState } from "react";
import { AssessmentResult, BusinessProfile, LoanApplication } from "../types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Progress } from "./ui/progress";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { CheckCircle2, AlertCircle, TrendingUp, DollarSign } from "lucide-react";
import LoanApplicationModal from "./LoanApplicationModal";

interface DashboardProps {
  profile: BusinessProfile;
  assessment: AssessmentResult | null;
  loans: LoanApplication[];
  onApplyLoan: (amount: number) => void;
}

export default function Dashboard({ profile, assessment, loans, onApplyLoan }: DashboardProps) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const data = [
    { name: 'Revenue', amount: profile.monthlyRevenue },
    { name: 'Expenses', amount: profile.monthlyExpenses },
    { name: 'Profit', amount: profile.monthlyRevenue - profile.monthlyExpenses },
  ];

  return (
    <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 space-y-8">
      <LoanApplicationModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)} 
        maxAmount={assessment?.loanEligibility.maxAmount || 0}
        onConfirm={onApplyLoan}
      />
      <header className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-neutral-900">{profile.businessName}</h1>
          <p className="text-neutral-500">{profile.location} • {profile.industry}</p>
        </div>
        <Badge variant={assessment?.potentialRating === 'exceptional' ? 'default' : 'secondary'} className="text-lg px-4 py-1">
          {assessment?.potentialRating.toUpperCase()} POTENTIAL
        </Badge>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Potential Score */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              Potential Score
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center py-6">
            <div className="relative h-32 w-32 flex items-center justify-center">
              <svg className="h-full w-full" viewBox="0 0 100 100">
                <circle className="text-neutral-100 stroke-current" strokeWidth="8" fill="transparent" r="40" cx="50" cy="50" />
                <circle className="text-primary stroke-current" strokeWidth="8" strokeLinecap="round" fill="transparent" r="40" cx="50" cy="50" 
                  style={{ strokeDasharray: 251.2, strokeDashoffset: 251.2 - (251.2 * (assessment?.score || 0)) / 100 }} />
              </svg>
              <span className="absolute text-3xl font-bold">{assessment?.score || 0}%</span>
            </div>
            <p className="mt-4 text-sm text-neutral-500 text-center">Based on industry trends and your business metrics.</p>
          </CardContent>
        </Card>

        {/* Financial Overview */}
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-primary" />
              Monthly Financials
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[200px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={data}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip />
                <Bar dataKey="amount" fill="#3b82f6" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* AI Analysis */}
        <Card>
          <CardHeader>
            <CardTitle>AI Business Analysis</CardTitle>
            <CardDescription>Insights generated by Gemini AI</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="prose prose-sm text-neutral-600">
              <p>{assessment?.analysis}</p>
            </div>
            <div className="space-y-2">
              <h4 className="font-semibold text-sm uppercase tracking-wider text-neutral-500">Recommendations</h4>
              <ul className="space-y-2">
                {assessment?.recommendations.map((rec, i) => (
                  <li key={i} className="flex gap-2 text-sm text-neutral-700">
                    <CheckCircle2 className="h-4 w-4 text-green-500 flex-shrink-0 mt-0.5" />
                    {rec}
                  </li>
                ))}
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Loan Eligibility */}
        <Card className="border-primary/20 bg-primary/5">
          <CardHeader>
            <CardTitle>Microloan Eligibility</CardTitle>
            <CardDescription>Personalized funding options</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {assessment?.loanEligibility.eligible ? (
              <>
                <div className="flex justify-between items-end">
                  <div>
                    <p className="text-sm text-neutral-500">Maximum Amount</p>
                    <p className="text-4xl font-bold text-primary">${assessment.loanEligibility.maxAmount.toLocaleString()}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-neutral-500">Interest Rate</p>
                    <p className="text-2xl font-semibold">{assessment.loanEligibility.interestRate}% APR</p>
                  </div>
                </div>
                <div className="p-4 bg-white rounded-lg border border-primary/10 text-sm text-neutral-600 italic">
                  "{assessment.loanEligibility.reasoning}"
                </div>
                <Button className="w-full py-6 text-lg" onClick={() => setIsModalOpen(true)}>
                  Apply for Loan Now
                </Button>
              </>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center space-y-4">
                <AlertCircle className="h-12 w-12 text-amber-500" />
                <div>
                  <h3 className="font-bold text-lg">Not Eligible Yet</h3>
                  <p className="text-neutral-500">Follow our recommendations to improve your score and become eligible for funding.</p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Loan History */}
      {loans.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Loan History</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {loans.map((loan) => (
                <div key={loan.id} className="flex items-center justify-between p-4 border rounded-lg">
                  <div>
                    <p className="font-bold">${loan.amount.toLocaleString()}</p>
                    <p className="text-xs text-neutral-500">Applied on {new Date(loan.appliedAt).toLocaleDateString()}</p>
                  </div>
                  <Badge variant={
                    loan.status === 'approved' ? 'default' : 
                    loan.status === 'pending' ? 'secondary' : 
                    loan.status === 'rejected' ? 'destructive' : 'outline'
                  }>
                    {loan.status.toUpperCase()}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
